# Generated by Django 4.2 on 2025-12-19 06:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_unit', models.CharField(choices=[('per_hour', 'Per Hour'), ('per_service', 'Per Service'), ('per_sqft', 'Per Square Foot'), ('per_item', 'Per Item'), ('fixed', 'Fixed Price')], default='per_hour', max_length=50)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_price_negotiable', models.BooleanField(default=False)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60, help_text='Estimated duration in minutes')),
                ('warranty_months', models.PositiveIntegerField(default=0, help_text='Service warranty in months')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='List of requirements from customer')),
                ('tools_needed', models.JSONField(blank=True, default=list, help_text='List of tools needed for the service')),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.TimeField(default='09:00:00')),
                ('available_to', models.TimeField(default='18:00:00')),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Icon class name (e.g., 'fa-plumbing', 'fa-bolt')", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_categories/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.JSONField(default=dict, help_text='Location details including address and coordinates')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed by Providers'), ('quotes_received', 'Quotes Received'), ('assigned', 'Assigned to Provider'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('images', models.JSONField(blank=True, default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='services.servicecategory')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('included_items', models.JSONField(default=list, help_text='List of items/services included in package')),
                ('validity_days', models.PositiveIntegerField(default=30, help_text='Package validity in days')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.serviceprovider'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['customer', 'status'], name='services_se_custome_d15da7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['category', 'status'], name='services_se_categor_635ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['preferred_date'], name='services_se_preferr_c3e595_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['slug'], name='services_se_slug_89aee3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['parent'], name='services_se_parent__9f4edc_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['provider', 'is_available'], name='services_se_provide_ea9944_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_available'], name='services_se_categor_0003d9_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['base_price'], name='services_se_base_pr_55be81_idx'),
        ),
    ]
