# Generated by Django 4.2 on 2025-12-19 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='service_categories',
            field=models.ManyToManyField(related_name='providers', through='providers.ProviderServiceCategory', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerservicecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='providerservicecategory',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.serviceprovider'),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='providers.serviceprovider'),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provideravailability',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='providers.serviceprovider'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['city', 'is_available'], name='providers_s_city_87de1c_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['average_rating'], name='providers_s_average_a5378d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['is_verified'], name='providers_s_is_veri_76cf43_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['user'], name='providers_s_user_id_c93567_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providerservicecategory',
            unique_together={('provider', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='provideravailability',
            unique_together={('provider', 'date', 'start_time')},
        ),
    ]
