# Generated by Django 4.2 on 2025-12-19 07:07

import apps.providers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='working_days',
            field=models.JSONField(default=apps.providers.models.ServiceProvider.default_working_days, help_text='Days of week when provider is available'),
        ),
    ]
